services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEMO_MODE: "true"
      GOTENBERG_URL: http://gotenberg:3000
    volumes:
      - ./generated:/app/generated
      - ./shared:/app/shared
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
